# Generated by Django 4.0.4 on 2022-06-10 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_alter_vehicle_book_no_alter_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='recondition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recondition_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recondition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recondition_transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
