# Generated by Django 4.0.4 on 2022-06-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_alter_expenses_recondition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recondition',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='recondition',
            name='renew_at',
        ),
        migrations.RemoveField(
            model_name='recondition',
            name='street',
        ),
    ]
