# Generated by Django 4.0.4 on 2022-06-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0004_remove_recondition_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recondition',
            name='expire_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recondition',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
