# Generated by Django 4.0.4 on 2022-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category'),
            preserve_default=False,
        ),
    ]
