# Generated by Django 4.0.4 on 2022-07-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0016_contact_alter_blog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_commision', to='recon.vehicle')),
            ],
        ),
    ]
