# Generated by Django 4.0.4 on 2022-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0019_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recondition',
            name='call',
            field=models.IntegerField(default=121),
            preserve_default=False,
        ),
    ]
