# Generated by Django 4.0.4 on 2022-07-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0020_recondition_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('bike_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='exchange')),
                ('detail', models.CharField(max_length=400)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_exchange', to='recon.vehicle')),
            ],
        ),
    ]
