# Generated by Django 4.0.4 on 2022-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0021_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='recondition',
            name='lat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recondition',
            name='long',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
